---
title: "Analysis of PsychAD single cell dataset with lucida"
subtitle: '[Lee, et al. (2025)](https://psych-ad.org)'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r format(Sys.time())`"
documentclass: article
vignette: >
  %\VignetteIndexEntry{Analysis of PsychAD single cell dataset with lucida}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
---

<!---

cd /hpc/users/hoffmg01/work/lucida_analysis
module load pandoc imagemagick

# rm -rf PsychAD_analysis_cache/

rmarkdown::render("PsychAD_analysis.Rmd")


\cp -f PsychAD_analysis.html ~/www/

http://hoffmg01.dmz.hpc.mssm.edu/PsychAD_analysis.html


# https://docs.google.com/spreadsheets/d/13T9QVoky6bUMDhupfrcXLavOtsLSNWF6/edit?gid=386465612#gid=386465612

# Recode each PsychAD file
SRC=/hpc/users/hoffmg01/work/GenomicDataStream_analysis/recode_h5ad.py 

OUT=/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/psychAD

for FILE in $(ls /sc/arion/projects/psychAD/NPS-AD/freeze2_rc/h5ad_final/*_2024-02*)
do
  OUTFILE=$OUT/$(basename $FILE .h5ad)_sort_CSC_lzf.h5ad
  $SRC --input $FILE --sortBy class,subclass,subtype,Channel,SubID --format CSC --compression lzf --out $OUTFILE
done



saveRDS(fit, file="/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/psychAD/fit.RDS")
saveRDS(fit.null, file="/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/psychAD/fit.null.RDS")


--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  lazy.cache = FALSE
)
```

```{r packages, cache=FALSE}
library(lucida)
library(SingleCellExperiment)
library(tidyverse)
library(ggplot2)

thm = theme_classic() +
    theme(aspect.ratio = 1, 
      plot.title = element_text(hjust = 0.5)) 
```

# Lucida analysis
```{r load, cache=FALSE}
file = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/psychAD/FULL_2024-02-01_18_49_sort_CSC_lzf.h5ad"
sce = readH5AD(file)

# Set string "NA" to NA values to exclude
sce$c02x[sce$c02x == "NA"] <- NA

# set Control to be baseline
sce$c02x = factor(sce$c02x, c("Control", "AD", "NA"))
```

```{r lucida}
# fit full model for differential expression
form = ~ c02x + Age + Sex + PMI + Brain_bank + (1|SubID)
fit = lucida(sce, form, cluster_id = "class", nReaders=8)
```

```{r lucida.null}
# fit null model for variance partitioning analysis
fit.null <- lucida(sce, ~ (1|SubID), cluster_id = "class", nReaders=8)
```

```{r vp, fig.height = 10, fig.width=12}
vp <- fitVarPart(fit, fit.null)

plotVarPart(sortCols(vp), ncol=4)
```




## Plots
```{r plotDispEsts, fig.height = 10, fig.width = 12}
plotDispEsts(fit, ncol=4)
```

```{r plotMA, fig.height = 10, fig.width = 12}
plotMA(fit, coef='c02xAD', ncol=4)
```

```{r plotVolcano, fig.height = 10, fig.width = 12}
plotVolcano(fit, coef='c02xAD', ncol=4)
```



# Results
```{r results}
results(fit, "c02xAD") %>%
  group_by(cluster_id) %>%
  summarize( n = n()) %>%
  ggplot(aes(n, cluster_id, fill=cluster_id)) +
    geom_bar(stat="identity") +
    thm +
    theme(aspect.ratio = 2, legend.position="none") +
    scale_x_continuous(limits=c(0,NA), expand=c(0,0)) +
    xlab("# genes expressed")

figDx = results(fit, "c02xAD") %>%
  group_by(cluster_id) %>%
  summarize( nSignif = sum(FDR < 0.05)) %>%
  ggplot(aes(nSignif, cluster_id, fill=cluster_id)) +
    geom_bar(stat="identity") +
    thm +
    theme(aspect.ratio = 2, legend.position="none") +
    scale_x_continuous(limits=c(0,NA), expand=c(0,0)) +
    xlab("# significant genes") +
    ggtitle("Disease")
figDx
```


# One cell type
```{r one, fig.height=7, fig.width=12}
library(cowplot)
library(aplot)
CT = "Immune"

fig1 = plotDispEsts(fit, cluster_ids = CT )
fig2 = plotVolcano(fit, coef='c02xAD', cluster_ids = CT)
fig3 = plotVarPart(sortCols(vp), cluster_ids = CT)
fig4 = plotTrendVP( fit, vp, "CountNoise", cluster_ids = CT)
plot_grid(fig1, fig2, fig3, fig4, ncol=3)

fig5 = plotForest(fit, coef="c02xAD", gene = "PTPRG")
fig5 + theme_classic()  + theme(aspect.ratio=1) | 
figDx + theme_classic() + theme(aspect.ratio=1, legend.position="none")
```




