---
title: "Simulation analysis"
subtitle: 'PsychAD'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r format(Sys.time())`"
documentclass: article
params: 
  path: "none"
output:
  BiocStyle::html_document:
    toc: false
    toc_float: false
---


<!---

# cd /sc/arion/work/hoffmg01/lucida_analysis/simulations

# rm -rf plot_results_PsychAD_cache/
ml pandoc imagemagick


# system("git pull")

path = "/sc/arion/scratch/hoffmg01/sims/PsychAD/constant/8_12_16_20_25_50_0/"
setwd(path)

out_dir = paste0(path, "plot_results_PsychAD/")
int_dir = paste0(path, "plot_results_PsychAD_inter/")

unlink(out_dir, recursive = TRUE)
unlink(int_dir, recursive = TRUE)

Rmd = "/sc/arion/work/hoffmg01/lucida_analysis/simulations/plot_results_PsychAD.Rmd"
rmarkdown::render(Rmd, 
  # output_dir = out_dir,
  # intermediates_dir = int_dir,
  params = list(path = path))



system("cp -f /sc/arion/work/hoffmg01/lucida_analysis/simulations/plot_results_PsychAD.html ~/www/")


https://hoffmg01.dmz.hpc.mssm.edu/plot_results_PsychAD.html


--->




```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  tidy = FALSE,
  fig.height = 20,
  fig.width = 12,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE
)
```


```{r packages, cache=FALSE}
library(arrow)
library(ggplot2)
library(tidyverse)
library(scattermore)
library(PRROC)
library(parallel)
library(cowplot)

thm = theme_classic(15) +
    theme(aspect.ratio = 1, 
      plot.title = element_text(hjust = 0.5)) 

colorMethods = c(
  "dreamlet" = "#2CA02CFF",
  "DESeq2" = "#D62728FF",
  "edgeR" = "#A020F0",
  "glmGamPoi"  = "#FF69B4",
  "nebula" = "#FF7F0EFF",
  "nebula (HL)" = "#c15a00",
  "MAST" = "gold",
  "lucida" = "#1F77B4FF",
  "lucida [1 step]" = "#BECFE6FF",
  "lucida [Bayesian]" = "#204e74",
  "lucida [pb]"       = "navy"
  )

# pie(rep(1, length(colorMethods)), col=colorMethods)
```


```{r read, cache=TRUE, eval=TRUE}
get_idx = Vectorize(function(x, i){
  strsplit(x, "_")[[1]][i]
})

CTs = c('EN_L6_CT', 'IN_SST', 'Astro', 'Oligo')

files = list.files(params$path, "res_sim_.*.parquet", full.names=TRUE)
files = grep("_time", files, invert=TRUE, value = TRUE)

df = mclapply(files, function(file){
  open_dataset(file) %>%
  collect %>%
  mutate(libScaleFactor = get_idx(simID, 3),
        N = get_idx(simID, 6)) 
}, mc.cores=12) %>%
  bind_rows %>%
  mutate(libScaleFactor = factor(as.numeric(libScaleFactor))) %>%
  mutate(N = factor(as.numeric(N))) %>%
  mutate(cluster_id = factor(cluster_id, CTs)) %>%
  mutate(Method = gsub("nebula_HL", "nebula (HL)", Method)) %>%
  mutate(Method = factor(Method, names(colorMethods)))

# keep only genes included in each result,
# for each sample size
#####################

df.tg = df %>%
  group_by(N) %>%
  summarize(target = length(unique(Method))) %>%
  data.frame %>%
  column_to_rownames('N')

keep = df %>%
  group_by(cluster_id, ID, simID, libScaleFactor, N) %>%
  summarize(n = n()) %>%
  mutate(ID2 = paste(cluster_id, ID, simID, libScaleFactor, N)) %>%
  mutate(target = df.tg[N,] ) %>%
  filter(n == target) %>%
  pull(ID2)

df <- df %>%
      filter(paste(cluster_id, ID, simID, libScaleFactor, N) %in% keep) %>% 
      mutate(cluster_id = factor(cluster_id, CTs))

# Assign for each row
#####################

if( sum(df$Method == "lucida") > 0 ){

  df_mu = df %>%
    filter(Method == "lucida") %>%
    select(ID, cluster_id, simID, mu)

  df = df %>%
        select(-mu) %>%
        inner_join( df_mu, by = c("ID", "cluster_id", "simID"))
}
```


# Resource usage
```{r resource.usage, fig.height=3, fig.width=8}
library(stringr)
files = list.files(paste0(params$path, "logs/"), "*out", full.names=TRUE)

df_logs = mclapply(files, function(file){

  tmp = basename(file) %>%
    gsub(".out", "", .) %>%
    gsub("nebula_HL", "nebulaHL", .) %>%
    strsplit("_") %>%
    unlist  %>%
    gsub("nebulaHL", "nebula (HL)", .)

  a = data.frame(N = as.numeric(tmp[1]), Method = tmp[4])

  cmd = paste("grep \"CPU time :\"", file)
  a$CPU.time =  system(cmd, intern=TRUE) %>%
    tail(1) %>%
    str_squish %>%
    strsplit(., " ") %>%
    sapply(., `[[`, 4) %>%
    as.numeric

  cmd = paste("grep \"Max Memory :\"", file)
  a$Mem.Mb = system(cmd, intern=TRUE) %>%
    tail(1) %>%
    str_squish %>%
    strsplit(., " ") %>%
    sapply(., `[[`, 4) %>%
    as.numeric

  cmd = paste("grep \"Run time :\"", file)
  a$Wall.time =  system(cmd, intern=TRUE) %>%
    tail(1) %>%
    str_squish %>%
    strsplit(., " ") %>%
    sapply(., `[[`, 4) %>%
    as.numeric

  as.data.frame(a)
  }, mc.cores=12) %>%
  bind_rows %>%
  as_tibble %>%
  filter(CPU.time > 5)

fig1 = df_logs %>%
  ggplot(aes(N, CPU.time / 60, color=Method)) +
    geom_point() +
    geom_smooth(method="lm", se=FALSE) +    
    theme_classic() +
    theme(aspect.ratio=1) +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_manual(values=colorMethods) +
    xlab("Sample size")+
    ylab("CPU time (minutes)")

fig2 = df_logs %>%
  ggplot(aes(N, Wall.time / 60, color=Method)) +
    geom_point() +
    geom_smooth(method="lm", se=FALSE) +    
    theme_classic() +
    theme(aspect.ratio=1) +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_manual(values=colorMethods) +
    xlab("Sample size")+
    ylab("Wall time (minutes)")

fig3 = df_logs %>%
  ggplot(aes(N, Mem.Mb/1000, color=Method)) +
    geom_point() +
    geom_smooth(method="lm", se=FALSE) +    
    theme_classic() +
    theme(aspect.ratio=1) +
    scale_x_log10() +
    ylim(0, NA) +
    scale_color_manual(values=colorMethods) +
    xlab("Sample size")+
    ylab("Memory usage (Gb)")

plot_grid(
  fig1 + theme(legend.position="none"), 
  fig2 + theme(legend.position="none"), 
  fig3 + theme(legend.position="none"), 
  labels=LETTERS[1:3],
  align = "vh",
  nrow = 1 )
```


# Results
## Coefficients
```{r Coefficients, fig.height=18}
# Beta 
target = df %>%
        filter(b.true != 0) %>%
        pull(b.true) %>%
        head(1)

if( length(target) > 0){
  ylim = 2*target
  df %>%
    filter(libScaleFactor == "1") %>%
    droplevels %>%
    mutate(x = c("Zero", target)[(b.true!=0)+1]) %>%
    mutate(x = factor(x, c("Zero", target))) %>%
    ggplot(aes(x, logFC, fill=Method)) +
      geom_boxplot(outlier.shape = NA) +
      thm +
      theme(legend.position = "none") +
      facet_wrap(~cluster_id) +
      scale_fill_manual(values = colorMethods) + 
      xlab("True beta value") +
      ylab("Estimated logFC") +
      geom_segment(aes(x = .7, y = 0, xend = 1.5, yend = 0), color = "grey60", linewidth = 1, linetype="dashed") +
      geom_segment(aes(x = 1.6, y = target, xend = 2.3, yend = target), color = "grey60", linewidth = 1, linetype="dashed") +
      coord_cartesian(ylim=c(-ylim, ylim)) +
      facet_grid(N ~ cluster_id) 
}
```

```{r coef2}
rMSE = function(x,y){
  sqrt(mean((x-y)^2))
}

fig.logFC.rMSE = df %>% 
  filter(libScaleFactor == "1") %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( logFC, b.true)) %>%
  ggplot(aes(N, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    # scale_y_sqrt(expand=c(0,0)) +
    ylab("rMSE of logFC") +
    # ggtitle("Estimating logFC") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(libScaleFactor ~ cluster_id, scale="free_y") +
    coord_cartesian(ylim=c(0, NA), expand=FALSE) +
    xlab("Sample size")
```

```{r coef3, fig.height=12, fig.width=12}
df %>% 
  # filter(Method != "MAST") %>%
  # filter(Method == "lucida") %>%
  # filter(libScaleFactor == "1") %>%
  # filter(cluster_id == "Astro") %>%
  mutate(Method = factor(Method, rev(levels(Method)))) %>%
  ggplot(aes(mu, (b.true - logFC)^2, color=Method, fill=Method)) +
    geom_smooth(se=TRUE, alpha = .1) +
    thm +  
    scale_color_manual(values = colorMethods) +
    scale_fill_manual(values = colorMethods) +
    scale_x_log10() +
    scale_y_log10() +
    xlab("Mean normalized counts") +
    ylab("Squared deviation of estimated logFC (log10 scale)") +
    facet_grid(N ~ cluster_id, scales="free_y")
```


## Theta
```{r theta}
df %>%
  filter(!is.na(theta.x)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  filter(libScaleFactor == "1") %>%
  filter(N == "50") %>%
  ggplot(aes(theta.y, pmin(1e4, theta.x), color=Method)) +
    geom_scattermore(pointsize=5) +
    thm +
    theme(legend.position="none") +
    facet_grid(Method ~ cluster_id) +
    xlab(bquote(Simulated~theta)) +
    ylab(bquote(Estimated~theta)) +
    scale_x_log10() +
    scale_y_log10() +
    geom_abline( slope=1, color="black") +
    scale_color_manual(values = colorMethods) 
```

```{r theta.trend, fig.height=12, fig.width=12}
df %>%
  filter(!is.na(theta.x), is.finite(theta.x)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  ggplot(aes(mu, (log(theta.x) - log(theta.y))^2, color=Method, fill=Method)) +
    geom_smooth(se=TRUE, alpha =.1) +
    thm +    
    scale_color_manual(values = colorMethods) +
    scale_fill_manual(values = colorMethods) +
    xlab("Mean normalized counts") +
    ylab("Squared deviation of log theta") +
    scale_x_log10() +
    scale_y_log10() +    
    facet_grid( N ~ cluster_id, scales="free_y") 
```


```{r fig.theta.rMSE}
fig.theta.rMSE = df %>% 
  group_by(N, Method, cluster_id, libScaleFactor) %>%
  summarize(rMSE = rMSE( log(pmin(1e4, theta.x)), log( theta.y))) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  ggplot(aes(N, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0, NA)) +
    ylab("rMSE of log(theta)") +
    #ggtitle(bquote(Estimating~theta)) +
    scale_fill_manual(values = colorMethods) +
    facet_grid(libScaleFactor ~ cluster_id, scales="free_y") +
    xlab("Sample size")
```

# sigSq_g
```{r other.plots}
df %>%
  filter(libScaleFactor == "1") %>%
  filter(N == "12") %>%
  filter(!is.na(sigSq_g.x)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  ggplot(aes(sigSq_g.y, sigSq_g.x, color=Method)) +
    geom_scattermore(pointsize=2) +
    thm +
    theme(legend.position="none") +
    facet_grid(Method ~ cluster_id) +
    xlab(bquote(Simulated~sigma[g]^2)) +
    ylab(bquote(Estimated~sigma[g]^2)) +
    scale_x_log10() +
    scale_y_log10() +
    geom_abline( slope=1, color="black")  +
    scale_color_manual(values = colorMethods) 

fig.sigSqg.rMSE = df %>% 
  # filter(libScaleFactor == "1") %>%
  # filter(N == "100") %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE(sigSq_g.y, sigSq_g.x)) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  ggplot(aes(N , rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE)+
    ylab("rMSE of sigSq_g") +
    # ggtitle(bquote(Estimating~sigma[g]^2)) +
    scale_fill_manual(values = colorMethods) +
    facet_grid( libScaleFactor ~ cluster_id) +
    xlab("Sample size")
```

```{r sigSqg.trend, fig.height=12, fig.width=12}
df %>%
  filter(libScaleFactor == "1") %>%
  filter(!is.na(sigSq_g.x)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  ggplot(aes(mu, abs((sigSq_g.x) - (sigSq_g.y)), color=Method, fill=Method)) +
    geom_smooth(se=TRUE, alpha = .1) +
    thm +    
    scale_color_manual(values = colorMethods) +
    scale_fill_manual(values = colorMethods) +
    facet_wrap(~cluster_id) +
    xlab("Mean normalized counts") +    
    ylab("Squared deviation of sigSq_g") +
    scale_x_log10() +
    facet_grid(N ~ cluster_id, scales="free_y") +    
    coord_cartesian(expand=FALSE, ylim=c(0, NA))
```

## AUPR
```{r AUPR, fig.height=15, fig.width=12}
# AUPR 
aupr = function(status, score){

  pr <- pr.curve(
    scores.class0 = score[status != 0], 
    scores.class1 = score[status == 0], 
    rand.compute = TRUE, 
    curve = TRUE)

  # 5. Calculate F1 scores for all points
  recall <- pr$curve[, 1]
  precision <- pr$curve[, 2]
  f1_scores <- 2 * (precision * recall) / (precision + recall)

  data.frame(AUPR = pr$auc.integral, 
    AUPR.rand = pr$rand$auc.integral,
    F1.max = max(f1_scores, na.rm = TRUE))
}

df_perf = df %>% 
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  filter(!is.na(FDR)) %>%
  summarize(aupr(b.true, -log10(P.Value)))

# df_perf %>%
#   ggplot(aes(libScaleFactor, AUPR, fill=Method)) +
#     geom_bar(stat="identity", position="dodge") +
#     thm +
#     coord_cartesian(expand=FALSE, ylim=c(0,1)) +
#     geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
#     ggtitle("Differential expression performance") +
#     scale_fill_manual(values = colorMethods) +
#     facet_grid(N ~ cluster_id)

fig.AUPR = df_perf %>%
  ggplot(aes(N, AUPR, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    # ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(libScaleFactor ~ cluster_id) +
    xlab("Sample size")

# df_perf %>%
#   ggplot(aes(libScaleFactor, F1.max, fill=Method)) +
#     geom_bar(stat="identity", position="dodge") +
#     thm +
#     coord_cartesian(expand=FALSE, ylim=c(0,1)) +
#     ggtitle("Differential expression performance") +
#     scale_fill_manual(values = colorMethods) +
#     facet_grid(N ~ cluster_id)

fig.F1max = df_perf %>%
  ggplot(aes(N, F1.max, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    # ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(libScaleFactor ~ cluster_id) +
    xlab("Sample size")


breaks <- df %>%
          filter(cluster_id == "IN_SST") %>%
          # filter(libScaleFactor == "5") %>%
          filter(!is.na(mu)) %>%
          pull(mu) %>%
          log10 %>%
          quantile(probs = seq(0, 1, by = 1/6), na.rm = TRUE)

#  df %>% 
#   filter(cluster_id == "IN_SST") %>%
#   filter(libScaleFactor == "5") %>%
#   filter(N == "100") %>%
#   filter(!is.na(mu)) %>%
#   mutate(bin = cut(log10(mu), breaks=breaks)) %>%
#   filter(!is.na(bin)) %>%
#   group_by(Method, cluster_id, bin, libScaleFactor) %>%
#   # filter(!is.na(FDR)) %>%
#   summarize(aupr(b.true, -log10(FDR)), n = n()) %>%
#   ggplot(aes(bin, AUPR, fill=Method)) +
#     geom_bar(stat="identity", position="dodge") +
#     thm +
#     coord_cartesian(expand=FALSE, ylim=c(0,1)) +
#     geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
#     ggtitle("Differential expression performance vs expr magnitude") +
#     scale_fill_manual(values = colorMethods) +
#     facet_grid( libScaleFactor ~ cluster_id )

# # ggsave(fig, file="~/www/test.pdf", width=16)

# df %>% 
#   filter(libScaleFactor == "5") %>%
#   filter(!is.na(mu)) %>%
#   mutate(bin = cut(log10(mu), breaks=breaks)) %>%
#   filter(!is.na(bin)) %>%
#   group_by(Method, cluster_id, bin, libScaleFactor, N) %>%
#   filter(!is.na(FDR)) %>%
#   summarize(aupr(b.true, -log10(FDR)), n = n()) %>%
#   ggplot(aes(bin, AUPR, fill=Method)) +
#     geom_bar(stat="identity", position="dodge") +
#     thm +
#     coord_cartesian(expand=FALSE, ylim=c(0,1)) +
#     geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
#     ggtitle("Differential expression performance vs expr magnitude") +
#     scale_fill_manual(values = colorMethods) +
#     facet_grid( N ~ cluster_id )
# ```



## False positive rate
```{r FPR, fig.width=12}
fig.FPR = df %>% 
  group_by(Method, cluster_id, libScaleFactor, N)  %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  summarize( FPR = sum(P.Value < 0.05) / length(P.Value), 
              np = length(P.Value),
              se = sqrt(FPR*(1-FPR)/np)) %>%
  ggplot(aes(N, FPR, fill=Method)) +
    geom_bar(stat="identity", position = position_dodge(width = 0.9)) +
    # geom_errorbar(aes(ymin = FPR - 1.96*se, 
    #   ymax = FPR + 1.96*se), width=0, position = position_dodge(width = 0.9)) +
    thm +
    coord_cartesian(expand=FALSE) +
    geom_hline(yintercept = 0.05, linetype="dashed", color="grey30", linewidth=1) +
    ylab("False positive rate") +
    scale_fill_manual(values = colorMethods) +
    facet_grid( libScaleFactor ~ cluster_id) +
    xlab("Sample size")
```

```{r QQ.plot}
ymax = 6
alpha = 0.05
df %>% 
  filter(libScaleFactor == "1") %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  mutate( expected = -log10(seq(n()) / (n() + 1)),
          observed = -log10(sort(P.Value))) %>%
          # ci_lower = -log10(qbeta(alpha/2, seq(n()), seq(n(),1))))
          # ci_upper = -log10(qbeta(1 - alpha/2, 1:n(), n():1))) 
   ggplot(aes(expected, observed)) +
    # geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper), fill = "grey80") +
    geom_abline(intercept = 0, slope = 1, color = "black") +
    labs(
      x = expression(Expected~~-log[10](italic(P))),
      y = expression(Observed~~-log[10](italic(P)))
    ) +
    geom_scattermore(aes(color=Method), pointsize=6) +
    theme_classic() +
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) +
    scale_color_manual(values = colorMethods) +
    facet_grid( libScaleFactor + N ~ cluster_id ) +
    coord_cartesian(xlim=c(0, NA), ylim=c(0, ymax), expand=FALSE)
```



```{r breaks, fig.height=10}
breaks <- df %>%
          filter(cluster_id == "IN_SST") %>%
          filter(!is.na(mu)) %>%
          pull(mu) %>%
          log10 %>%
          quantile(probs = seq(.02, 1, by = .1), na.rm = TRUE)

df %>% 
  filter(cluster_id == "IN_SST") %>%
  # filter(libScaleFactor == "1") %>%
  # filter(libScaleFactor != "25") %>%
  filter(N == "50") %>%
  filter(!is.na(mu)) %>%
  mutate(bin = cut(log10(mu), breaks=breaks)) %>%
  filter(!is.na(bin)) %>%
  group_by(Method, cluster_id, bin, libScaleFactor)  %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  summarize( FPR = sum(P.Value < 0.05) / length(P.Value), 
    N = length(P.Value),
    se = sqrt(FPR*(1-FPR)/N)) %>%
  ggplot(aes(bin, FPR, fill=Method)) +
    geom_bar(stat="identity", position = position_dodge(width = 0.9)) +
    geom_errorbar(aes(ymin = FPR - 1.96*se, 
      ymax = FPR + 1.96*se), width=0, position = position_dodge(width = 0.9)) +
    thm +
    coord_cartesian(expand=FALSE) +
    geom_hline(yintercept = 0.05, linetype="dashed", color="grey30", linewidth=1) +
    ylab("False positive rate") +
    scale_fill_manual(values = colorMethods) +
    facet_grid( libScaleFactor ~ cluster_id ) 
```


## Combined
```{r combined, fig.width=10, fig.height=16, cache=FALSE}
plot_grid(
  fig.logFC.rMSE, 
  fig.theta.rMSE,
  fig.sigSqg.rMSE,
  fig.FPR, 
  fig.AUPR,
  fig.F1max,
  ncol=1,
  labels = LETTERS[1:6],
  align = "vh")
```






<!---
## Subset
--->

```{r panel1, fig.height=4, eval=FALSE, echo=FALSE}
library(aplot)

df_sub = df %>% 
  # filter(libScaleFactor == "5") %>%
  filter(N == "50") %>%
  filter(cluster_id == "Oligo") %>%
  filter(Method != "lucida [pb]") %>%
  filter(Method != "lucida [1 step]")

table(df_sub$Method)

fig1 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( logFC, b.true)) %>%
  ggplot(aes(libScaleFactor, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    # scale_y_sqrt(expand=c(0,0)) +
    ylab("rMSE of estimated logFC") +
    # ggtitle("Estimating logFC") +
    scale_fill_manual(values = colorMethods) +
    scale_y_continuous(limits=c(0, NA), expand=c(0,0))

fig2 = df_sub %>%
  mutate(Method = factor(Method, rev(levels(Method)))) %>%
  ggplot(aes(mu, (b.true - logFC)^2, color=Method)) +
    geom_smooth(se=FALSE, lwd=2) +
    thm +  
    theme(legend.position="none") +
    scale_color_manual(values = colorMethods) +
    # ggtitle("Squared deviation of estimate logFC vs expression magnitude") +
    scale_x_log10() +
    xlab("Mean normalized counts") +
    ylab("Squared dev. of estimated logFC (log10 scale)") +
    scale_y_log10() 

fig3 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( log(theta.x), log(theta.y))) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  ggplot(aes(libScaleFactor, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0, NA)) +
    ylab(bquote(rMSE~log(mu^2/theta))) +
    ggtitle(bquote(Estimating~theta)) +
    scale_fill_manual(values = colorMethods) 

fig4 = df_sub %>%
  filter(!is.na(theta.x)) %>%
  filter(Method %in% c("nebula", "nebula (HL)", "lucida", "lucida [1 step]")) %>%
  mutate(dev = (log(theta.y) - log(theta.x))^2) %>%
  mutate(Method = factor(Method, rev(levels(Method)))) %>%
  ggplot(aes(mu, dev, color=Method)) +
    geom_smooth(se=TRUE, alpha = .1, aes(fill=Method), lwd=2) +
    thm +    
    theme(legend.position="none") +
    scale_color_manual(values = colorMethods) +
    scale_fill_manual(values = colorMethods) +
    xlab("Mean normalized counts") +
    ylab("Squared dev. of log(theta)") +
    scale_x_log10() +
    coord_cartesian(expand=FALSE, ylim=c(0, 0.05))

fig5 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( sigSq_g.y, sigSq_g.x)) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(libScaleFactor , rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    theme(legend.position="none") +
    coord_cartesian(expand=FALSE)+
    ylab("Root mean squared error") +
    # ggtitle(bquote(Estimating~sigma[g]^2)) +
    scale_fill_manual(values = colorMethods) 


fig6 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N)  %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  summarize( FPR = sum(P.Value < 0.05) / length(P.Value), 
              np = length(P.Value),
              se = sqrt(FPR*(1-FPR)/np)) %>%
  ggplot(aes(libScaleFactor, FPR, fill=Method)) +
    geom_bar(stat="identity", position = position_dodge(width = 0.9)) +
    geom_errorbar(aes(ymin = FPR - 1.96*se, 
      ymax = FPR + 1.96*se), width=0, position = position_dodge(width = 0.9)) +
    thm +
    coord_cartesian(expand=FALSE) +
    geom_hline(yintercept = 0.05, linetype="dashed", color="grey30", linewidth=1) +
    ylab("False positive rate") +
    scale_fill_manual(values = colorMethods) 


df_perf_sub = df_perf %>% 
  # filter(libScaleFactor == "5") %>%
  filter(cluster_id == "Oligo") %>%
  filter(Method != "lucida [pb]") %>%
  filter(Method != "lucida [1 step]")

fig7 = df_perf_sub %>%
  ggplot(aes(N, AUPR, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    theme(legend.position="none") +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) 

fig1 | fig2 
fig3 | fig4 
fig5
fig6 | fig7
```


#### Session info
<details>
```{r sessionInfo}
sessionInfo()
```
</details>





