---
title: "Simulation analysis"
subtitle: '1k1k'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r format(Sys.time())`"
documentclass: article
output:
  BiocStyle::html_document:
    toc: false
    toc_float: false
---


<!---

# cd /sc/arion/work/hoffmg01/lucida_analysis/simulations

# rm -rf plot_results_cache/
ml pandoc imagemagick

rmarkdown::render("plot_results.Rmd")

system("cp -f plot_results.html ~/www/")

https://hoffmg01.dmz.hpc.mssm.edu/plot_results.html

thm = theme_classic(30) +
    theme(aspect.ratio = 1, 
      plot.title = element_text(hjust = 0.5)) 


--->




```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  tidy = FALSE,
  fig.height = 20,
  fig.width = 12,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE
)
```


```{r packages, cache=FALSE}
library(arrow)
library(ggplot2)
library(tidyverse)
library(scattermore)
library(PRROC)
library(parallel)

thm = theme_classic(15) +
    theme(aspect.ratio = 1, 
      plot.title = element_text(hjust = 0.5)) 

colorMethods = c(
  "nebula" = "#FF7F0EFF",
  "nebula (HL)" = "#c15a00",
  "dreamlet" = "#2CA02CFF",
  "DESeq2" = "#D62728FF",
  "edgeR" = "#A020F0",
  "glmGamPoi"  = "#FF69B4",
  "lucida" = "#1F77B4FF",
  "lucida [1 step]" = "#BECFE6FF",
  "lucida [Bayesian]" = "#204e74",
  "lucida [pb]"       = "navy",
  )

# pie(rep(1, length(colorMethods)), col=colorMethods)
```


```{r read, cache=TRUE, eval=TRUE}
get_idx = Vectorize(function(x, i){
  strsplit(x, "_")[[1]][i]
})

CTs = c("mucosal invariant T cell", "gamma-delta T cell", "naive B cell", "naive thymus-derived CD4-positive, alpha-beta T cell")

files = list.files("/sc/arion/scratch/hoffmg01/sims/1k1k_v1/constant", "res_sim_.*.parquet", full.names=TRUE)
files = grep("_time", files, invert=TRUE, value = TRUE)

df = mclapply(files, function(file){
  open_dataset(file) %>%
  collect %>%
  mutate(libScaleFactor = get_idx(simID, 3),
        N = get_idx(simID, 6)) 
}, mc.cores=12) %>%
  bind_rows %>%
  mutate(libScaleFactor = factor(as.numeric(libScaleFactor))) %>%
  mutate(N = factor(as.numeric(N))) %>%
  mutate(cluster_id = factor(cluster_id, CTs))%>%
  mutate(Method = factor(Method, names(colorMethods)))

table(df$libScaleFactor)

# count genes retained by each method
# df %>%
#   filter(N == "8", libScaleFactor == "25", cluster_id == "naive B cell") %>%
#   group_by(Method, libScaleFactor, N, cluster_id) %>%
#   summarize(n = n()) %>%
#   ggplot(aes(Method, n, fill=Method)) +
#     geom_bar(stat="identity") +
#     thm +
#     theme(legend.position="none") + 
#     scale_fill_manual(values = colorMethods) + 
#     ylab("Number of genes retained") +
#     # facet_grid(N~libScaleFactor) +
#     facet_grid(N ~ cluster_id)

# keep only genes included in each result
target = length(unique(df$Method))
keep1 <- df %>%
  group_by(cluster_id, ID, simID, libScaleFactor, N) %>%
  summarize(n = n()) %>%
  mutate(ID2 = paste(cluster_id, ID, simID, libScaleFactor, N)) %>%
  filter( n == target ) %>%
  pull(ID2)

# For small samples, nebula is omitted
# target = df %>%
#           filter(N %in% c("4", "8")) %>%
#           pull(Method) %>%
#           unique %>%
#           length

# keep2 <- df %>%
#   filter(N %in% c("4", "8")) %>%
#   group_by(cluster_id, ID, simID, libScaleFactor, N) %>%
#   summarize(n = n()) %>%
#   mutate(ID2 = paste(cluster_id, ID, simID, libScaleFactor, N)) %>%
#   filter( n == target ) %>%
#   pull(ID2)

# keep = unique(c(keep1, keep2))
keep = keep1

df <- df %>%
      filter(paste(cluster_id, ID, simID, libScaleFactor, N) %in% keep) %>% 
      mutate(cluster_id = factor(cluster_id, CTs))
```




```{r read2, eval=FALSE, cache=FALSE}
# write_parquet(df, "df.paruqet")

# rsync -avPz minerva:/sc/arion/work/hoffmg01/lucida_analysis/simulations/df.paruqet ~/workspace/repos/lucida_analysis/simulations/1k1k_v1/

CTs = c("mucosal invariant T cell", "gamma-delta T cell", "naive B cell", "naive thymus-derived CD4-positive, alpha-beta T cell")

file = "/Users/gabrielhoffman/workspace/repos/lucida_analysis/simulations/1k1k_v1/df.paruqet"
# file = "/sc/arion/work/hoffmg01/lucida_analysis/simulations/df.paruqet"
df = read_parquet(file)

```

# Time
```{r time, fig.height=5, fig.width=12}
files = list.files("/sc/arion/scratch/hoffmg01/sims/1k1k_v1/trajectory", "res_sim_.*.parquet", full.names=TRUE)
files = grep("_time", files, value = TRUE)

pb.methods = c("lucida [pb]", "dreamlet")#, "DESeq2", "edgeR")

df_time = mclapply(files, function(file){
  a = read_parquet(file) 

  pb = a %>%
    filter(Method == "pseudobulk")

  for(mth in pb.methods){
    i = which(a$Method == mth)
    a$user.self[i] = a$user.self[i] + pb$user.self 
    a$sys.self[i] = a$sys.self[i] + pb$sys.self 
    a$elapsed[i] = a$elapsed[i] + pb$elapsed 
    a$user.child[i] = a$user.child[i] + pb$user.child 
    a$sys.child[i] = a$sys.child[i] + pb$sys.child 
  }

  a %>%
    filter(Method != "pseudobulk")

}, mc.cores=12) %>%
  bind_rows %>%
  mutate(libScaleFactor = get_idx(simID, 3)) %>%
  mutate(N = get_idx(simID, 6)) %>%
  mutate(libScaleFactor = factor(as.numeric(libScaleFactor))) %>%
  mutate(Method = factor(Method, names(colorMethods)))

df_time %>%
  mutate(N = as.numeric(N)) %>%
  filter(libScaleFactor == 1) %>%
  ggplot(aes(N, elapsed, color=Method)) +
    geom_point() +
    geom_smooth(method="lm", se=FALSE) +    
    theme_classic() +
    theme(aspect.ratio=1) +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_manual(values=colorMethods) +
    facet_wrap(~libScaleFactor, nrow=1) 
```


# Results
## Coefficients
```{r Coefficients, fig.height=18}
# Beta 
target = df %>%
        filter(b.true != 0) %>%
        pull(b.true) %>%
        head(1)

ylim = .2
df %>%
  filter(libScaleFactor == "1") %>%
  droplevels %>%
  mutate(x = c("Zero", target)[(b.true!=0)+1]) %>%
  mutate(x = factor(x, c("Zero", target))) %>%
  ggplot(aes(x, logFC, fill=Method)) +
    geom_boxplot(outlier.shape = NA) +
    thm +
    theme(legend.position = "none") +
    facet_wrap(~cluster_id) +
    scale_fill_manual(values = colorMethods) + 
    xlab("True beta value") +
    ylab("Estimated logFC") +
    geom_segment(aes(x = .7, y = 0, xend = 1.5, yend = 0), color = "grey60", linewidth = 1, linetype="dashed") +
    geom_segment(aes(x = 1.6, y = target, xend = 2.3, yend = target), color = "grey60", linewidth = 1, linetype="dashed") +
    coord_cartesian(ylim=c(-ylim, ylim)) +
    facet_grid(N ~ cluster_id) 
```

```{r coef2}
rMSE = function(x,y){
  sqrt(mean((x-y)^2))
}

df %>% 
  filter(libScaleFactor == "1") %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( logFC, b.true)) %>%
  ggplot(aes(libScaleFactor, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    # scale_y_sqrt(expand=c(0,0)) +
    ylab("Root mean squared error of estimated logFC") +
    ggtitle("Estimating logFC") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(N ~ cluster_id, scale="free_y") +
    scale_y_continuous(limits=c(0, NA), expand=c(0,0))
```

```{r coef3, fig.height=12, fig.width=12}
df %>% 
  filter(libScaleFactor == "1") %>%
  # filter(N == "250") %>%
  mutate(Method = factor(Method, rev(levels(Method)))) %>%
  ggplot(aes(mu, (b.true - logFC)^2, color=Method)) +
    geom_smooth(se=FALSE) +
    thm +  
    scale_color_manual(values = colorMethods) +
    ggtitle("Squared deviation of estimate logFC vs expression magnitude") +
    scale_x_log10() +
    xlab("Mean normalized counts") +
    ylab("Squared deviation of estimated logFC (log10 scale)") +
    facet_grid(N ~ cluster_id, scales="free_y") + 
    scale_y_log10() 
```








## Theta
```{r theta, eval=TRUE}
df %>%
  filter(!is.na(theta.x)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  filter(libScaleFactor == "1") %>%
  filter(N == "250") %>%
  ggplot(aes(theta.y, pmin(1e4, theta.x), color=Method)) +
    geom_scattermore(pointsize=5) +
    thm +
    theme(legend.position="none") +
    facet_grid(Method ~ cluster_id) +
    xlab(bquote(Simulated~theta)) +
    ylab(bquote(Estimated~theta)) +
    scale_x_log10() +
    scale_y_log10() +
    geom_abline( slope=1, color="black") +
    scale_color_manual(values = colorMethods) +
    facet_grid(Method ~ cluster_id )

df %>%
  filter(libScaleFactor == "1") %>%
  filter(N == "250") %>%
  filter(!is.na(theta.x)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(mu, (log(theta.x) - log(theta.y))^2, color=Method)) +
    geom_smooth(se=FALSE, method = "loess") +
    thm +    
    scale_color_manual(values = colorMethods) +
    xlab("Mean normalized counts") +
    ylab("Squared deviation of log theta") +
    scale_x_log10() +
    facet_grid( ~ cluster_id) +
    scale_y_continuous() +
    coord_cartesian(expand=FALSE, ylim=c(-.1, 5)) 

df %>% 
  filter(N == "250") %>%
  group_by(Method, cluster_id, libScaleFactor) %>%
  summarize(rMSE = rMSE( pmin(1e4, theta.x), theta.y)) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(libScaleFactor, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0, NA)) +
    ylab("Root mean squared error") +
    ggtitle(bquote(Estimating~theta)) +
    scale_fill_manual(values = colorMethods) +
    facet_grid(~cluster_id)
```

## Theta (normalized)
The variance of the negative binomial distribution is $\mu + \mu^2/theta$.  So once $\theta$ reaches a sufficient value, the log-likelihood becomes very flat because for moderately sized $\mu$, $\mu + \mu^2/1e4 \approx \mu + \mu^2/1e5$.  Therefore, show the estimate of $\mu^2/theta$ instead.

```{r theta.normalized, fig.width=18, fig.height=12, eval=FALSE}
df %>%
  filter(libScaleFactor == "1") %>%
  filter(N == "250") %>%
  filter(!is.na(theta.x)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(mu^2/theta.y, mu^2/theta.x, color=Method)) +
    geom_abline( slope=1, color="black") +
    geom_scattermore(pointsize=4) +
    thm +
    theme(legend.position="none") +
    facet_grid(Method ~ cluster_id) +
    xlab(bquote(Simulated~mu^2/theta)) +
    ylab(bquote(Estimated~mu^2/theta)) +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_manual(values = colorMethods) +
    facet_grid(Method ~ cluster_id)
```

```{r theta.normalized2, fig.width=13, fig.height=12}
df %>%
  filter(libScaleFactor == "1") %>%
  # filter(N == "250") %>%
  filter(!is.na(theta.x)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  mutate(dev = (log(mu^2/theta.y) - log(mu^2/theta.x))^2) %>%
  mutate(Method = factor(Method, rev(levels(Method)))) %>%
  ggplot(aes(mu, dev, color=Method)) +
    geom_smooth(se=FALSE, alpha = .15, aes(fill=Method)) +
    thm +    
    scale_color_manual(values = colorMethods) +
    scale_fill_manual(values = colorMethods) +
    xlab("Mean normalized counts") +
    ylab("Squared deviation of log(mu^2/theta)") +
    scale_x_log10() +
    facet_grid(N ~ cluster_id, scales="free_y") +
    coord_cartesian(expand=FALSE, ylim=c(-0.1, 20)) 

df %>% 
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( log(mu^2/theta.x), log(mu^2/theta.y))) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(libScaleFactor, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0, NA)) +
    ylab(bquote(rMSE~log(mu^2/theta))) +
    ggtitle(bquote(Estimating~overdispersion~component~mu^2/theta)) +
    scale_fill_manual(values = colorMethods) +
    facet_grid(N ~ cluster_id)
```

# sigSq_g
```{r other.plots, eval=FALSE}
df %>%
  filter(libScaleFactor == "1") %>%
  filter(N == "250") %>%
  filter(!is.na(sigSq_g.x)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(sigSq_g.y, sigSq_g.x, color=Method)) +
    geom_scattermore(pointsize=2) +
    thm +
    theme(legend.position="none") +
    facet_grid(Method ~ cluster_id) +
    xlab(bquote(Simulated~sigma[g]^2)) +
    ylab(bquote(Estimated~sigma[g]^2)) +
    scale_x_log10() +
    scale_y_log10() +
    geom_abline( slope=1, color="black")  +
    scale_color_manual(values = colorMethods) + 
    facet_grid(Method ~ cluster_id)

df %>% 
  # filter(libScaleFactor == "1") %>%
  # filter(N == "250") %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( sigSq_g.y, sigSq_g.x)) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(libScaleFactor , rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE)+
    ylab("Root mean squared error") +
    ggtitle(bquote(Estimating~sigma[g]^2)) +
    scale_fill_manual(values = colorMethods) +
    # scale_y_sqrt() +
    facet_grid(N ~ cluster_id) 

df %>%
  filter(libScaleFactor == "1") %>%
  # filter(N == "250") %>%
  # filter(!is.na(sigSq_g.x)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(mu, abs((sigSq_g.x) - (sigSq_g.y)), color=Method)) +
    # geom_point() +
    geom_smooth(se=FALSE) +
    thm +    
    scale_color_manual(values = colorMethods) +
    facet_wrap(~cluster_id) +
    xlab("Mean normalized counts") +    
    ylab("Squared deviation of sigSq_g") +
    scale_x_log10() +
    facet_grid(libScaleFactor ~ cluster_id) 
```

## AUPR
```{r AUPR, fig.height=15, fig.width=12}
# AUPR 
aupr = function(status, score){

  pr <- pr.curve(
    scores.class0 = score[status != 0], 
    scores.class1 = score[status == 0], 
    rand.compute = TRUE, 
    curve = TRUE)

  # 5. Calculate F1 scores for all points
  recall <- pr$curve[, 1]
  precision <- pr$curve[, 2]
  f1_scores <- 2 * (precision * recall) / (precision + recall)

  data.frame(AUPR = pr$auc.integral, 
    AUPR.rand = pr$rand$auc.integral,
    F1.max = max(f1_scores, na.rm = TRUE))
}

df_perf = df %>% 
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  filter(!is.na(FDR)) %>%
  summarize(aupr(b.true, -log10(FDR)))

df_perf %>%
  ggplot(aes(libScaleFactor, AUPR, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(N ~ cluster_id)

df_perf %>%
  ggplot(aes(N, AUPR, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(libScaleFactor ~ cluster_id)

df_perf %>%
  ggplot(aes(libScaleFactor, F1.max, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(N ~ cluster_id)

df_perf %>%
  ggplot(aes(N, F1.max, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(libScaleFactor ~ cluster_id)


breaks <- df %>%
          filter(!is.na(mu)) %>%
          pull(mu) %>%
          log10 %>%
          quantile(probs = seq(0, 1, by = 1/3), na.rm = TRUE)

df %>% 
  filter(N == "250") %>%
  filter(!is.na(mu)) %>%
  mutate(bin = cut(log10(mu), breaks=breaks)) %>%
  filter(!is.na(bin)) %>%
  group_by(Method, cluster_id, bin, libScaleFactor) %>%
  filter(!is.na(FDR)) %>%
  summarize(aupr(b.true, -log10(FDR)), n = n()) %>%
  ggplot(aes(bin, AUPR, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    ggtitle("Differential expression performance vs expr magnitude") +
    scale_fill_manual(values = colorMethods) +
    facet_grid( libScaleFactor ~ cluster_id )

df %>% 
  filter(libScaleFactor == "1") %>%
  filter(!is.na(mu)) %>%
  mutate(bin = cut(log10(mu), breaks=breaks)) %>%
  filter(!is.na(bin)) %>%
  group_by(Method, cluster_id, bin, libScaleFactor, N) %>%
  filter(!is.na(FDR)) %>%
  summarize(aupr(b.true, -log10(FDR)), n = n()) %>%
  ggplot(aes(bin, AUPR, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    ggtitle("Differential expression performance vs expr magnitude") +
    scale_fill_manual(values = colorMethods) +
    facet_grid( N ~ cluster_id )



```



## False positive rate
```{r FPR, fig.height=15, fig.width=12}
df %>% 
  # filter(libScaleFactor == "1") %>%
  # filter(N == "250") %>%
  group_by(Method, cluster_id, libScaleFactor, N)  %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  summarize( FPR = sum(P.Value < 0.05) / length(P.Value), 
              np = length(P.Value),
              se = sqrt(FPR*(1-FPR)/np)) %>%
  ggplot(aes(libScaleFactor, FPR, fill=Method)) +
    geom_bar(stat="identity", position = position_dodge(width = 0.9)) +
    geom_errorbar(aes(ymin = FPR - 1.96*se, 
      ymax = FPR + 1.96*se), width=0, position = position_dodge(width = 0.9)) +
    thm +
    coord_cartesian(expand=FALSE) +
    geom_hline(yintercept = 0.05, linetype="dashed", color="grey30", linewidth=1) +
    ylab("False positive rate") +
    scale_fill_manual(values = colorMethods) +
    facet_grid(N ~ cluster_id)
```

```{r QQ.plot}
ymax = 6
alpha = 0.05
df %>% 
  filter(libScaleFactor == "1") %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  mutate( expected = -log10(seq(n()) / (n() + 1)),
          observed = -log10(sort(P.Value))) %>%
          # ci_lower = -log10(qbeta(alpha/2, seq(n()), seq(n(),1))))
          # ci_upper = -log10(qbeta(1 - alpha/2, 1:n(), n():1))) 
   ggplot(aes(expected, observed)) +
    # geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper), fill = "grey80") +
    geom_abline(intercept = 0, slope = 1, color = "black") +
    labs(
      x = expression(Expected~~-log[10](italic(P))),
      y = expression(Observed~~-log[10](italic(P)))
    ) +
    geom_scattermore(aes(color=Method), pointsize=6) +
    theme_classic() +
    theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5)) +
    scale_color_manual(values = colorMethods) +
    facet_grid( libScaleFactor + N ~ cluster_id ) +
    coord_cartesian(xlim=c(0, NA), ylim=c(0, ymax), expand=FALSE)
```



```{r breaks, fig.height=10}
breaks <- df %>%
          filter(!is.na(mu)) %>%
          pull(mu) %>%
          log10 %>%
          quantile(probs = seq(0, 1, by = 1/3), na.rm = TRUE)

df %>% 
  # filter(libScaleFactor == "1") %>%
  filter(libScaleFactor != "25") %>%
  filter(N == "250") %>%
  filter(!is.na(mu)) %>%
  mutate(bin = cut(log10(mu), breaks=breaks)) %>%
  filter(!is.na(bin)) %>%
  group_by(Method, cluster_id, bin, libScaleFactor)  %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  summarize( FPR = sum(P.Value < 0.05) / length(P.Value), 
    N = length(P.Value),
    se = sqrt(FPR*(1-FPR)/N)) %>%
  ggplot(aes(bin, FPR, fill=Method)) +
    geom_bar(stat="identity", position = position_dodge(width = 0.9)) +
    geom_errorbar(aes(ymin = FPR - 1.96*se, 
      ymax = FPR + 1.96*se), width=0, position = position_dodge(width = 0.9)) +
    thm +
    coord_cartesian(expand=FALSE) +
    geom_hline(yintercept = 0.05, linetype="dashed", color="grey30", linewidth=1) +
    ylab("False positive rate") +
    scale_fill_manual(values = colorMethods) +
    facet_grid( libScaleFactor ~ cluster_id )
```













```{r panel1}

library(aplot)

df_sub = df %>% 
  filter(libScaleFactor == "5") %>%
  filter(N == "100") %>%
  filter(cluster_id == "gamma-delta T cell") %>%
  filter(Method != "lucida [pb]") %>%
  filter(Method != "lucida [1 step]")

table(df_sub$Method)



fig1 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( logFC, b.true)) %>%
  ggplot(aes(libScaleFactor, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    # scale_y_sqrt(expand=c(0,0)) +
    ylab("Root mean squared error of estimated logFC") +
    ggtitle("Estimating logFC") +
    scale_fill_manual(values = colorMethods) +
    scale_y_continuous(limits=c(0, NA), expand=c(0,0))

fig2 = df_sub %>%
  mutate(Method = factor(Method, rev(levels(Method)))) %>%
  ggplot(aes(mu, (b.true - logFC)^2, color=Method)) +
    geom_smooth(se=FALSE, lwd=2) +
    thm +  
    theme(legend.position="none") +
    scale_color_manual(values = colorMethods) +
    ggtitle("Squared deviation of estimate logFC vs expression magnitude") +
    scale_x_log10() +
    xlab("Mean normalized counts") +
    ylab("Squared deviation of estimated logFC (log10 scale)") +
    scale_y_log10() 

fig3 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( log(mu^2/theta.x), log(mu^2/theta.y))) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(libScaleFactor, rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    coord_cartesian(expand=FALSE, ylim=c(0, NA)) +
    ylab(bquote(rMSE~log(mu^2/theta))) +
    ggtitle(bquote(Estimating~overdispersion~component~mu^2/theta)) +
    scale_fill_manual(values = colorMethods) 

fig4 = df_sub %>%
  filter(!is.na(theta.x)) %>%
  mutate(dev = (log(mu^2/theta.y) - log(mu^2/theta.x))^2) %>%
  mutate(Method = factor(Method, rev(levels(Method)))) %>%
  ggplot(aes(mu, dev, color=Method)) +
    geom_smooth(se=FALSE, alpha = .15, aes(fill=Method), lwd=2) +
    thm +    
    theme(legend.position="none") +
    scale_color_manual(values = colorMethods) +
    scale_fill_manual(values = colorMethods) +
    xlab("Mean normalized counts") +
    ylab("Squared deviation of log(mu^2/theta)") +
    scale_x_log10() +
    coord_cartesian(expand=FALSE, ylim=c(-0.1, 20)) 

fig5 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N) %>%
  summarize(rMSE = rMSE( sigSq_g.y, sigSq_g.x)) %>%
  filter(!is.na(rMSE)) %>%
  filter(Method != "lucida [Bayesian]") %>%
  ggplot(aes(libScaleFactor , rMSE, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    theme(legend.position="none") +
    coord_cartesian(expand=FALSE)+
    ylab("Root mean squared error") +
    ggtitle(bquote(Estimating~sigma[g]^2)) +
    scale_fill_manual(values = colorMethods) 


fig6 = df_sub %>%
  group_by(Method, cluster_id, libScaleFactor, N)  %>%
  filter(!is.na(P.Value), b.true == 0) %>% 
  summarize( FPR = sum(P.Value < 0.05) / length(P.Value), 
              np = length(P.Value),
              se = sqrt(FPR*(1-FPR)/np)) %>%
  ggplot(aes(libScaleFactor, FPR, fill=Method)) +
    geom_bar(stat="identity", position = position_dodge(width = 0.9)) +
    geom_errorbar(aes(ymin = FPR - 1.96*se, 
      ymax = FPR + 1.96*se), width=0, position = position_dodge(width = 0.9)) +
    thm +
    coord_cartesian(expand=FALSE) +
    geom_hline(yintercept = 0.05, linetype="dashed", color="grey30", linewidth=1) +
    ylab("False positive rate") +
    scale_fill_manual(values = colorMethods) 


df_perf_sub = df_perf %>% 
  filter(libScaleFactor == "5") %>%
  filter(cluster_id == "gamma-delta T cell") %>%
  filter(Method != "lucida [pb]") %>%
  filter(Method != "lucida [1 step]")

fig7 = df_perf_sub %>%
  ggplot(aes(N, AUPR, fill=Method)) +
    geom_bar(stat="identity", position="dodge") +
    thm +
    theme(legend.position="none") +
    coord_cartesian(expand=FALSE, ylim=c(0,1)) +
    geom_hline(yintercept = 0.1, linetype="dashed", color="grey30", linewidth=1) +
    ggtitle("Differential expression performance") +
    scale_fill_manual(values = colorMethods) 

file = "~/www/test.pdf"
pdf(file, width=16)
fig1 | fig2 
fig3 | fig4 
fig5
fig6 | fig7
dev.off()




```





